### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-Markdown#1]
Markdown is much more than an input format for HTML, please consider using Pandoc in this modules: it contains a JSON format to represent Markdown. The current fix name should better make clear that it converts to HTML.

**Comment by nicolasfranck** [comment]
I renamed it to markdown_to_html.

For the moment, I only need a simple perl module for converting to html,
so it works out of the box, without needing to install a binary command line
tool.

**Comment by nichtich** [comment]
Thanks! By the way the best method to import the abstract syntax of Markdown is to use Pandoc:

`echo '[hello](http://example.org)' | pandoc -t json | catmandu convert JSON to YAML`

``` yaml
---
- unMeta: {}
- - c:
    - c:
      - - c: hello
          t: Str
      - - http://example.org
        - ''
      t: Link
    t: Para
```
